language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
sudo: false
install:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O $HOME/miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh;
    fi
    bash $HOME/miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    mkdir -p $HOME/.config/matplotlib
    echo "backend: agg" > $HOME/.config/matplotlib/matplotlibrc
    hash -r
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
    conda install conda-build
    conda info -a
  - |
    conda create -q -n py$TRAVIS_PYTHON_VERSION python=$TRAVIS_PYTHON_VERSION
    source activate py$TRAVIS_PYTHON_VERSION
  - conda build .
  - conda install rayopt --use-local
script:
  - python -m unittest discover rayopt.test
notifications:
  email:
    on_success: never
    on_failure: never
