package:
  name: rayopt
  version: "0.0"

source:
  # path: .
  git_rev: master
  git_url: https://github.com/jordens/rayopt.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - scipy
    - pyyaml
    - matplotlib
    - sqlalchemy
  run:
    - python
    - cython
    - numpy
    - scipy
    - pyyaml
    - matplotlib
    - sqlalchemy

build:
  number: 1
  string: dev
  script: python setup.py install

test:
  imports:
    - rayopt
#  commands:
#    - python -m unittest discover rayopt

about:
  home: https://github.com/jordens/rayopt
  license: GPL3
  license_file: COPYING
